collections:
  - name: 'portfolios' # Used in routes, e.g., /admin/collections/portfolios
    label: 'Portfolios' # Used in the UI
    folder: 'src/data/portfolios' # The path to the folder where the documents are stored
    extension: md
    create: true # Allow users to create new documents in this collection
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
    fields: # The fields for each document, usually in frontmatter
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Headline', name: 'description', widget: 'markdown' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Hero Image', name: 'heroImage', widget: 'image' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Location', name: 'location', widget: 'string' }
      - {
          label: 'Clients',
          name: 'clients',
          widget: 'list',
          field: [{ label: 'Client', name: 'client', widget: 'string' }],
        }
      - {
          label: 'Rows',
          label_singular: 'Row',
          name: 'images',
          widget: 'list',
          fields:
            [
              {
                label: 'Images',
                label_singular: 'Image',
                name: 'row',
                widget: 'list',
                field: { label: 'Image', name: 'image', widget: 'image' },
              },
            ],
        }
media_folder: 'src/assets/images' # Location where files will be stored in the repo
public_folder: '@assets/images' # The src attribute for uploaded media
backend:
  name: github
  repo: eventistca/site-mombo-productions
  base_url: https://sveltia-cms-auth.tiedye1.workers.dev/
